[build-system]
requires = ["setuptools>=61.0", "torch"]
build-backend = "setuptools.build_meta"

[project]
dependencies = [
    "torch",
    "ucimlrepo",
    "scikit-learn",
    "pandas",
    "numpy",
]
